FROM amazoncorretto:17-alpine
VOLUME /doko

ARG JAR_FILE
ARG AWS_ACCESS_KEY_ID_BUILD
ARG AWS_SECRET_KEY_BUILD

RUN echo $AWS_ACCESS_KEY_ID_BUILD
RUN echo $AWS_SECRET_KEY_BUILD

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_BUILD}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY_BUILD}

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]