FROM amazoncorretto:17-alpine
VOLUME /doko

ARG JAR_FILE
ARG AWS_ACCESS_KEY_ID_INPUT
ARG AWS_SECRET_KEY_INPUT

RUN echo $AWS_ACCESS_KEY_ID_INPUT
RUN echo $AWS_SECRET_KEY_INPUT

ENV AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID_INPUT}
ENV AWS_SECRET_KEY=${AWS_SECRET_KEY_INPUT}

COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]